# Map_GA variables
MAP_POPULATION_SIZE = 1000
MAP_AMOUNT_OF_PARENTS_CHOSEN = 1000  # if this is not the same as MAP_POP_SIZE randoms will be put into the parent list
MIN_AREAS_IN_CITY = 1
MAX_AREAS_IN_CITY = 10
MAP_GENERATION_AMOUNT = 200
MAP_ELITISM_AMOUNT = 10
MAP_MUTATION_PERCENTAGE = 1

# Fitness
#  Size Fitness
FITNESS_SIZE_VALUE_MULTIPLIER = 20
#  Distance Fitness
FITNESS_DISTANCE_MAX_SCORE = 200
FITNESS_DISTANCE_MAX_ALLOWED_DISTANCE_BEFORE_MINUS = 100
#  Altitude Fitness
FITNESS_ALTITUDE_MAX_SCORE = 200
FITNESS_ALTITUDE_MAX_ALLOWED_DIFFERENCE_BEFORE_MINUS = 3
#  Amount Fitness
FITNESS_AMOUNT_BONUS_PER_EXTRA = 25
