from minecraft_pb2 import *

# Box area (they are made to be inclusive)
"""Nicolai's coordinates"""
# BOX_X_MIN = 232055
# BOX_X_MAX = 232105
# BOX_Z_MIN = 23232900
# BOX_Z_MAX = 23232950
"""Jonas' coordinates"""
# Showcases:
# BOX_X_MIN = 150
# BOX_X_MAX = 350
# BOX_Z_MIN = 1900
# BOX_Z_MAX = 2100
# ------
# BOX_X_MIN = 170
# BOX_X_MAX = 370
# BOX_Z_MIN = 2240
# BOX_Z_MAX = 2440
# ------
# BOX_X_MIN = 260
# BOX_X_MAX = 460
# BOX_Z_MIN = 2490
# BOX_Z_MAX = 2690
# A* Test coordinates
# BOX_X_MIN = 100
# BOX_X_MAX = 300
# BOX_Z_MIN = 1500
# BOX_Z_MAX = 1700
# Smaller Test
# BOX_X_MIN = 100
# BOX_X_MAX = 200
# BOX_Z_MIN = 1500
# BOX_Z_MAX = 1600
"""Mikkel's coordinates"""
BOX_X_MIN = -153 #-245
BOX_X_MAX = 96   #4
BOX_Z_MIN = 1411 #1483
BOX_Z_MAX = 1661 #1733
# BOX_X_MIN = 237  # -293 #  -243  # -153 #-245
# BOX_X_MAX = 358  # -143 #  -43   # 96   #4
# BOX_Z_MIN = 852  # 1246 #  1355  # 1411 #1483
# BOX_Z_MAX = 986  # 1495 #  1591  # 1661 #1733
# # Mikkel square test
# BOX_X_MIN = 113
# BOX_X_MAX = 213
# BOX_Z_MIN = 1512
# BOX_Z_MAX = 1613


# Map analysis
MIN_SIZE_OF_AREA = 20


# List of blocks that is ignored
SKIP_SET = {DARK_OAK_DOOR, IRON_DOOR, BIRCH_DOOR, JUNGLE_DOOR, ACACIA_DOOR, SPRUCE_DOOR, WOODEN_DOOR, IRON_TRAPDOOR,
            TRAPDOOR, FENCE, BIRCH_FENCE, ACACIA_FENCE, JUNGLE_FENCE, DARK_OAK_FENCE, NETHER_BRICK_FENCE,
            SPRUCE_FENCE, FENCE_GATE, BIRCH_FENCE_GATE, ACACIA_FENCE_GATE, JUNGLE_FENCE_GATE, DARK_OAK_FENCE_GATE,
            SPRUCE_FENCE_GATE, CARPET, COBBLESTONE_WALL, NETHER_WART, STANDING_BANNER, WALL_BANNER, STANDING_SIGN,
            WALL_SIGN, WOODEN_BUTTON, STONE_BUTTON, TRIPWIRE, AIR, BEETROOTS, TALLGRASS, RED_FLOWER, YELLOW_FLOWER,
            CHORUS_FLOWER, LEAVES, LEAVES2, VINE, SAPLING, WATERLILY, RED_MUSHROOM, BROWN_MUSHROOM, REEDS, POTATOES,
            MELON_BLOCK, MELON_STEM, PUMPKIN_STEM, PUMPKIN, DEADBUSH, SNOW_LAYER, WHEAT, RAIL, CHORUS_PLANT,
            DOUBLE_PLANT, FIRE, COCOA, CARROTS, CACTUS, TORCH}


FLUID_SET = {WATER, FLOWING_WATER, LAVA, FLOWING_LAVA, BEDROCK}

save_file_dir = '../data/'
save_file_path = 'block_dicts.pkl'


